# Generated by Django 5.1.5 on 2025-01-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technologies'), ('life', 'Life'), ('edu', 'Education')], default='tech', max_length=10),
        ),
    ]
